dj_scraping/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("scrape.urls")),
]

scrape/urls.py
from django.urls import path
from . import views

app_name = "scrape"

urlpatterns = [
    #path("", views.index, name="home"),
    path("", views.GetData.as_view(), name="home"),
    path("download/<uuid:uuid>/", views.downloader, name="downloader"),
]

scrape/models.py
from django.db import models


class Request(models.Model):
    url = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(null=True)

scrape/forms.py
from django import forms
from .models import Request

class RequestForm(forms.ModelForm):
    
    class Meta:
        model = Request
        fields = ("url",)

scrape/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from .forms import RequestForm
from django.views import generic
import uuid
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
from .models import Request

def get_yahooauction(url):
    res = requests.get(url)
    soup = bs(res.content, "html.parser")
    items = soup.findAll("li", class_="Product")
    return[
        {
            "title": item.find("a",class_="product__titleLink"),
            "url": item.find("a",class_="Product__titleLink").get("href"),
            "picture": item.find("img").get("src")
        }
        for item in items
    ]

class GetData(generic.FormView):
    template_name = "scrape/index.html"
    form_class = RequestForm

    def form_valid(self, form):
        # uuidを生成
        _uuid = uuid.uuid4()
        gcs_bucket = "gs://yuw5296"
        # formオブジェクトを初期化
        f = form.save(commit=False)
        # formにuuidを代入       
        f.uuid = _uuid
        # formを保存
        f.save()
        url = form.cleaned_data["url"]
        # スクレイピング
        result = get_yahooauction(url)
        df = pd.DataFrame(result)
        # file名を定義
        filename = f"{gcs_bucket}/{_uuid}test.pkl"
        # save data
        df.to_pickle(filename)

        context = {
            "url": form.cleaned_data["url"],
            "form": self.form_class,
            "name": f"スクレイピング {datetime.today()}",
            "result": Request.objects.all().order_by("-date")
        }
        return render(
            self.request, 
            self.template_name,
            context
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["name"] = f"スクレイピング {datetime.today()}"
        context["result"] = Request.objects.all().order_by("-date")
        return context

def downloader(request, uuid):
    gcs_bucket = "gs://yuw5296"
    filename = f"{gcs_bucket}/{uuid}test.pkl"
    df = pd.read_pickle(filename)

    res = HttpResponse(content_type="text/csv; charset=utf-8")
    file_name = f"{datetime.today()}_dj.csv"
    res["Content-Disposition"] = f"attachment; filename*=UTF-8\'\'{file_name}"
    df.to_csv(res, index=False)

    return res

scrape/templates/scrape/index.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>

<div class="container">
    <h1>課題 {{name}}</h1>
    <hr>
    <form action="/" method="POST">
        {{form.as_p}}
        <hr>
        {% csrf_token %}
        <button type="submit">送信</button>
</form>
<br>
<hr>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>url</th>
            <th>date</th>
            <th>uuid</th>            
        </tr>
    </thead>
    <tbody>
        {% for res in result %}
            {% if res.uuid is not None %}
            <tr>
                <td>{{res.url}}</td>
                <td>{{res.date}}</td>
                <td>
                    <a href="{% url 'scrape:downloader' uuid=res.uuid %}">{{res.uuid}}</a>
                </td>
            </tr>
            {% endif %}
        {% endfor %}

    </tbody>
</table> 

</div>